import json, os

OUT = 'results/exp2_modality_removal'
os.makedirs(OUT, exist_ok=True)

data = [
    ('c2former','rgb','brightness_shift',1,'rgb_only','tir',0.4302),
    ('c2former','rgb','brightness_shift',1,'tir_only','rgb',0.3875),
    ('c2former','rgb','brightness_shift',2,'rgb_only','tir',0.4072),
    ('c2former','rgb','brightness_shift',2,'tir_only','rgb',0.3875),
    ('c2former','rgb','brightness_shift',3,'rgb_only','tir',0.356),
    ('c2former','rgb','brightness_shift',3,'tir_only','rgb',0.3875),
    ('c2former','rgb','complete_dropout',None,'rgb_only','tir',0.0),
    ('c2former','rgb','complete_dropout',None,'tir_only','rgb',0.3875),
    ('c2former','rgb','gaussian_noise',1,'rgb_only','tir',0.3263),
    ('c2former','rgb','gaussian_noise',1,'tir_only','rgb',0.3875),
    ('c2former','rgb','gaussian_noise',2,'rgb_only','tir',0.2595),
    ('c2former','rgb','gaussian_noise',2,'tir_only','rgb',0.3875),
    ('c2former','rgb','gaussian_noise',3,'rgb_only','tir',0.17),
    ('c2former','rgb','gaussian_noise',3,'tir_only','rgb',0.3875),
    ('c2former','rgb','low_contrast',1,'rgb_only','tir',0.3503),
    ('c2former','rgb','low_contrast',1,'tir_only','rgb',0.3875),
    ('c2former','rgb','low_contrast',2,'rgb_only','tir',0.3044),
    ('c2former','rgb','low_contrast',2,'tir_only','rgb',0.3875),
    ('c2former','rgb','low_contrast',3,'rgb_only','tir',0.2577),
    ('c2former','rgb','low_contrast',3,'tir_only','rgb',0.3875),
    ('c2former','rgb','motion_blur',1,'rgb_only','tir',0.3886),
    ('c2former','rgb','motion_blur',1,'tir_only','rgb',0.3875),
    ('c2former','rgb','motion_blur',2,'rgb_only','tir',0.3391),
    ('c2former','rgb','motion_blur',2,'tir_only','rgb',0.3875),
    ('c2former','rgb','motion_blur',3,'rgb_only','tir',0.2646),
    ('c2former','rgb','motion_blur',3,'tir_only','rgb',0.3875),
    ('c2former','tir','blur',1,'rgb_only','tir',0.4339),
    ('c2former','tir','blur',1,'tir_only','rgb',0.3477),
    ('c2former','tir','blur',2,'rgb_only','tir',0.4339),
    ('c2former','tir','blur',2,'tir_only','rgb',0.2515),
    ('c2former','tir','blur',3,'rgb_only','tir',0.4339),
    ('c2former','tir','blur',3,'tir_only','rgb',0.1522),
    ('c2former','tir','complete_dropout',None,'rgb_only','tir',0.4339),
    ('c2former','tir','complete_dropout',None,'tir_only','rgb',0.0),
    ('c2former','tir','intensity_shift',1,'rgb_only','tir',0.4339),
    ('c2former','tir','intensity_shift',1,'tir_only','rgb',0.398),
    ('c2former','tir','intensity_shift',2,'rgb_only','tir',0.4339),
    ('c2former','tir','intensity_shift',2,'tir_only','rgb',0.3685),
    ('c2former','tir','intensity_shift',3,'rgb_only','tir',0.4339),
    ('c2former','tir','intensity_shift',3,'tir_only','rgb',0.3267),
    ('c2former','tir','sensor_noise',1,'rgb_only','tir',0.4339),
    ('c2former','tir','sensor_noise',1,'tir_only','rgb',0.2817),
    ('c2former','tir','sensor_noise',2,'rgb_only','tir',0.4339),
    ('c2former','tir','sensor_noise',2,'tir_only','rgb',0.2145),
    ('c2former','tir','sensor_noise',3,'rgb_only','tir',0.4339),
    ('c2former','tir','sensor_noise',3,'tir_only','rgb',0.0819),
    ('early_fusion','rgb','brightness_shift',1,'rgb_only','tir',0.1322),
    ('early_fusion','rgb','brightness_shift',1,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','brightness_shift',2,'rgb_only','tir',0.1276),
    ('early_fusion','rgb','brightness_shift',2,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','brightness_shift',3,'rgb_only','tir',0.0945),
    ('early_fusion','rgb','brightness_shift',3,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','complete_dropout',None,'rgb_only','tir',0.0),
    ('early_fusion','rgb','complete_dropout',None,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','gaussian_noise',1,'rgb_only','tir',0.1164),
    ('early_fusion','rgb','gaussian_noise',1,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','gaussian_noise',2,'rgb_only','tir',0.1263),
    ('early_fusion','rgb','gaussian_noise',2,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','gaussian_noise',3,'rgb_only','tir',0.0778),
    ('early_fusion','rgb','gaussian_noise',3,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','low_contrast',1,'rgb_only','tir',0.0251),
    ('early_fusion','rgb','low_contrast',1,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','low_contrast',2,'rgb_only','tir',0.0273),
    ('early_fusion','rgb','low_contrast',2,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','low_contrast',3,'rgb_only','tir',0.0),
    ('early_fusion','rgb','low_contrast',3,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','motion_blur',1,'rgb_only','tir',0.1125),
    ('early_fusion','rgb','motion_blur',1,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','motion_blur',2,'rgb_only','tir',0.0916),
    ('early_fusion','rgb','motion_blur',2,'tir_only','rgb',0.2977),
    ('early_fusion','rgb','motion_blur',3,'rgb_only','tir',0.0736),
    ('early_fusion','rgb','motion_blur',3,'tir_only','rgb',0.2977),
    ('early_fusion','tir','blur',1,'rgb_only','tir',0.1499),
    ('early_fusion','tir','blur',1,'tir_only','rgb',0.2967),
    ('early_fusion','tir','blur',2,'rgb_only','tir',0.1499),
    ('early_fusion','tir','blur',2,'tir_only','rgb',0.2788),
    ('early_fusion','tir','blur',3,'rgb_only','tir',0.1499),
    ('early_fusion','tir','blur',3,'tir_only','rgb',0.2506),
    ('early_fusion','tir','complete_dropout',None,'rgb_only','tir',0.1499),
    ('early_fusion','tir','complete_dropout',None,'tir_only','rgb',0.0),
    ('early_fusion','tir','intensity_shift',1,'rgb_only','tir',0.1499),
    ('early_fusion','tir','intensity_shift',1,'tir_only','rgb',0.2977),
    ('early_fusion','tir','intensity_shift',2,'rgb_only','tir',0.1499),
    ('early_fusion','tir','intensity_shift',2,'tir_only','rgb',0.2977),
    ('early_fusion','tir','intensity_shift',3,'rgb_only','tir',0.1499),
    ('early_fusion','tir','intensity_shift',3,'tir_only','rgb',0.2977),
    ('early_fusion','tir','sensor_noise',1,'rgb_only','tir',0.1499),
    ('early_fusion','tir','sensor_noise',1,'tir_only','rgb',0.2657),
    ('early_fusion','tir','sensor_noise',2,'rgb_only','tir',0.1499),
    ('early_fusion','tir','sensor_noise',2,'tir_only','rgb',0.2484),
    ('early_fusion','tir','sensor_noise',3,'rgb_only','tir',0.1499),
    ('early_fusion','tir','sensor_noise',3,'tir_only','rgb',0.1663),
]

for model, mod, corr, sev, config, zeroed, map_val in data:
    sev_str = 'sdropout' if sev is None else str(sev)
    fname = f'{model}__{mod}__{corr}__s{sev_str}__{config}.json'
    obj = {'model': model, 'modality': mod, 'corruption': corr,
           'severity': sev, 'config': config, 'zeroed_stream': zeroed, 'map': map_val}
    with open(f'{OUT}/{fname}', 'w') as f:
        json.dump(obj, f, indent=2)

print(f'Written {len(data)} files to {OUT}/')
